server {
  listen 80;
  server_name _;
  add_header Permissions-Policy "browsing-topics=(), join-ad-interest-group=(), run-ad-auction=()" always;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /assets/ {
    expires 1y;
    add_header Cache-Control "public, immutable";
  }
}
